name: Build And Push A Single Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "The Service To Build"
        required: true
        type: choice
        options:
          - offchain-actions
          - strategy-builder
          - onchain-listener
          - frontend
          - sqs-orchestrator
          - data-provider
          - integration-provider
          - integration-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::010073361729:role/cdk-hnb659fds-image-publishing-role-010073361729-us-east-1
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        id: build-and-push
        run: |
          service_name=${{ inputs.service_name }}
          dir=services/$service_name
          docker buildx build --platform linux/amd64 -t $service_name "$dir"
          docker tag $service_name "${{ steps.ecr_login.outputs.registry }}/$service_name"
          docker push "${{ steps.ecr_login.outputs.registry }}/$service_name"
