name: Build And Push A Single App

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "The App To Build"
        required: true
        type: choice
        options:
          - frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Create Enviorment Variables
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::010073361729:role/cdk-hnb659fds-image-publishing-role-010073361729-us-east-1
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        id: build-and-push
        run: |
          app_name=${{ inputs.app_name }}
          docker buildx build --platform linux/amd64 -f apps/$app_name/Dockerfile -t $app_name .
          docker tag $app_name "${{ steps.ecr_login.outputs.registry }}/$app_name"
          docker push "${{ steps.ecr_login.outputs.registry }}/$app_name"
